

name: Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

env:

  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: europe-west1 
  GAR_REPOSITORY: ai-outreach-agent-repo 
  IMAGE_NAME: api-server

jobs:
  build-and-push-to-gcp:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4


    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}


    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'


    - name: Authorize Docker push
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev


    - name: Build and Push Image to GAR
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest